# Docker Compose file for testing against the [MapR Container for Developers](https://maprdocs.mapr.com/home/MapRContainerDevelopers/MapRContainerDevelopersOverview.html)

# Connect UI to http://localhost:8080 to see "Last messages - refreshed every 3 seconds"

version: "3"

services:

  producer:
    network_mode: "bridge"
    build:
      context: sensor-service
    image: mapr-sensor-producer
    environment:
      - MAPR_CLDB_HOSTS=host.docker.internal
      - MAPR_CLUSTER=maprdemo.mapr.io
      - MAPR_CONTAINER_USER=mapr
    

  web:
    network_mode: "bridge"
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    devices:
      - /dev/fuse
    build:
      context: webserver-service
    image: mapr-web-consumer
    environment:
      - MAPR_CLDB_HOSTS=host.docker.internal
      - MAPR_CLUSTER=maprdemo.mapr.io
      - MAPR_CONTAINER_USER=mapr
      - MAPR_MOUNT_PATH=/mapr
    ports:
      - "8080:8080"
